[package]
name          = "socket2"
version       = "0.4.0-dev"
authors       = ["Alex Crichton <alex@alexcrichton.com>"]
license       = "MIT/Apache-2.0"
readme        = "README.md"
repository    = "https://github.com/rust-lang/socket2-rs"
homepage      = "https://github.com/rust-lang/socket2-rs"
documentation = "https://docs.rs/socket2"
description = """
Utilities for handling networking sockets with a maximal amount of configuration
possible intended.
"""
keywords      = ["io", "socket", "network"]
categories    = ["api-bindings", "network-programming"]
edition       = "2018"
include       = [
  "Cargo.toml",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "README.md",
  "src/**/*.rs",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.playground]
features = ["all"]

[target."cfg(windows)".dependencies.winapi]
version = "0.3.3"
features = ["handleapi", "ws2def", "ws2ipdef", "ws2tcpip", "minwindef"]

[target."cfg(any(unix, target_os = \"redox\"))".dependencies]
cfg-if = "1.0.0"
libc = "0.2.66"

[target."cfg(target_os = \"redox\")".dependencies]
redox_syscall = "0.1.38"

[dev-dependencies]
tempdir = "0.3"

[features]
# Enable all API, even ones not available on all OSes.
all = []
